spring:
  application:
    name: lovable-clone
    description: This is a fullstack application called lovable clone

  datasource:
    url: jdbc:postgresql://localhost:5433/lovable
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080

  ## Adding some dummy data in the database to ensure some data is present in the database